name:                docserver
version:             0.1.0.0
github:              ""
license:             BSD3
author:              "Jean-Christophe Mincke"
maintainer:          "jeanchristophe.mincke@gmail.com"
copyright:           "2020 Jean-Christophe Mincke"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README.

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  docserver-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - docserver

tests:
  docserver-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - docserver
